# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TORI
email: tori.erc.project@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  TORI develops the next generation data reduction tools based on topological data analysis. TORI is supported by the European Research Council (ERC).
#Write an awesome description for your new site here. You can edit this
#line in _config.yml. It will appear in your document head meta (for
#Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erc-tori.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: JulienTierny
#github_username:  julien-tierny

# Build settings
theme: minima
#theme: minima

navigation:
  - title: Home
    url: index.html
  - title: Team
    url: team.html
  - title: Publications
    url: publications.html

markdown: kramdown
  
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-twitter-plugin

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
